version: "3.9"

services:
  flask-server:
    build: .
    restart: always
    volumes:
      - ./app/frames/:/app/frames
      - ./app/processed/:/app/processed
      - ./app/uploads/:/app/uploads
    env_file:
      - .env
    ports:
      - "5001:5001"
